wayne: configs: vintf: Remove vendor.qti.gnss hal
error: Cannot add manifest fragment /vendor/etc/vintf/manifest/vendor.qti.gnss@4.0-service.xml:
HAL "vendor.qti.gnss" has a conflict: Conflicting FqInstance: @1.2::ILocHidlGnss/gnss_vendor
 (from /vendor/etc/vintf/manifest.xml) vs. @1.2::ILocHidlGnss/gnss_vendor (from /vendor/etc
/vintf/manifest/vendor.qti.gnss@4.0-service.xml). Check whether or not multiple modules
providing the same HAL are installed.

Multiple conflicts in: https://github.com/Diva-Room/Miku_vendor_xiaomi_wayne/blob/TDA/Android.bp#L458

Change-Id: Ia150357e00bfb577f0d2275ad26ccdcd06be13d0
Signed-off-by: xiaoleGun <1592501605@qq.com>